import { Suspense } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Provider from "@/providers/Provider";
import { LoaderProvider } from "@/providers/LoaderProvider";
import "./globals.css";
import 'aos/dist/aos.css'; // You can also use <link> for styles

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#1b1c26]`}
      >
        <Suspense fallback={null}>
          <LoaderProvider>
            <Provider>
              {children}
            </Provider>
          </LoaderProvider>
        </Suspense>
      </body>
    </html>
  );
}
